# Generated by Django 5.2.8 on 2025-11-25 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_knowledgeembedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('command', models.CharField(help_text="Команда запуска MCP сервера, например 'uvx' или 'node' или 'python'", max_length=255)),
                ('command_args', models.JSONField(default=list, help_text="Список аргументов, например ['mcp-server-filesystem', '--root', '/app/data']")),
                ('transport', models.CharField(choices=[('stdio', 'STDIO'), ('http', 'HTTP')], default='stdio', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MCP сервер',
                'verbose_name_plural': 'MCP серверы',
            },
        ),
        migrations.CreateModel(
            name='MCPTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('input_schema', models.JSONField(blank=True, default=dict)),
                ('output_schema', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='core.mcpserver')),
            ],
            options={
                'unique_together': {('server', 'name')},
            },
        ),
    ]
