# Generated by Django 5.2.8 on 2025-11-25 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mcpserver_mcptool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('system_prompt', models.TextField(blank=True)),
                ('model_name', models.CharField(default='gpt-4.1-mini', max_length=100)),
                ('temperature', models.FloatField(default=0.2, help_text='Креативность модели (0.0–1.0)')),
                ('max_tokens', models.IntegerField(blank=True, help_text='Ограничение длины ответа модели; null = по умолчанию модели', null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, help_text='null = глобальный агент', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='core.project')),
            ],
            options={
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AgentServerBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_tools', models.JSONField(default=list, help_text='Список имён MCPTool.name, которые агент может вызывать')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_bindings', to='core.agent')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_bindings', to='core.mcpserver')),
            ],
            options={
                'unique_together': {('agent', 'server')},
            },
        ),
    ]
