# Generated by Django 5.2.8 on 2025-11-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_pipeline_task_pipelinestep"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcpserver",
            name="base_url",
            field=models.URLField(
                blank=True,
                null=True,
                verbose_name="Базовый URL MCP сервера",
                help_text="Например: http://filesystem-mcp:8015/mcp (для HTTP-транспорта)",
            ),
        ),
    ]

