# Generated by Django 5.2.8 on 2025-11-26 06:53

import core.models
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_mcpserver_base_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'Агент', 'verbose_name_plural': 'Агенты'},
        ),
        migrations.AlterModelOptions(
            name='agentserverbinding',
            options={'verbose_name': 'Доступ агента к MCP', 'verbose_name_plural': 'Доступы агентов к MCP'},
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Диалог', 'verbose_name_plural': 'Диалоги'},
        ),
        migrations.AlterModelOptions(
            name='knowledgebase',
            options={'verbose_name': 'База знаний', 'verbose_name_plural': 'Базы знаний'},
        ),
        migrations.AlterModelOptions(
            name='knowledgechunk',
            options={'ordering': ['chunk_index'], 'verbose_name': 'Фрагмент', 'verbose_name_plural': 'Фрагменты'},
        ),
        migrations.AlterModelOptions(
            name='knowledgedocument',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='knowledgeembedding',
            options={'verbose_name': 'Эмбеддинг (фрагмент)', 'verbose_name_plural': 'Эмбеддинги (фрагменты)'},
        ),
        migrations.AlterModelOptions(
            name='mcpserver',
            options={'verbose_name': 'MCP-сервер', 'verbose_name_plural': 'MCP-серверы'},
        ),
        migrations.AlterModelOptions(
            name='mcptool',
            options={'verbose_name': 'Инструмент MCP', 'verbose_name_plural': 'Инструменты MCP'},
        ),
        migrations.AlterModelOptions(
            name='memoryembedding',
            options={'verbose_name': 'Эмбеддинг (память)', 'verbose_name_plural': 'Эмбеддинги (память)'},
        ),
        migrations.AlterModelOptions(
            name='memoryevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Память', 'verbose_name_plural': 'Память'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='pipeline',
            options={'ordering': ['name'], 'verbose_name': 'Пайплайн', 'verbose_name_plural': 'Пайплайны'},
        ),
        migrations.AlterModelOptions(
            name='pipelinestep',
            options={'ordering': ['order'], 'verbose_name': 'Шаг пайплайна', 'verbose_name_plural': 'Шаги пайплайнов'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterField(
            model_name='agent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Агент по умолчанию'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='max_tokens',
            field=models.IntegerField(blank=True, help_text='Ограничение длины ответа модели; null = по умолчанию модели', null=True, verbose_name='Максимум токенов'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='model_name',
            field=models.CharField(blank=True, default='', help_text='LLM модель, например: gpt-5.1. Пусто = использовать модель по умолчанию из реестра.', max_length=100, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя агента'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='project',
            field=models.ForeignKey(blank=True, help_text='null = глобальный агент', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='core.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='system_prompt',
            field=models.TextField(blank=True, verbose_name='Системный промпт'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='temperature',
            field=models.FloatField(default=0.2, help_text='Креативность модели (0.0–1.0)', verbose_name='Температура'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='agentserverbinding',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_bindings', to='core.agent', verbose_name='Агент'),
        ),
        migrations.AlterField(
            model_name='agentserverbinding',
            name='allowed_tools',
            field=models.JSONField(default=list, help_text='Список имён MCPTool.name, которые агент может вызывать', verbose_name='Разрешённые инструменты'),
        ),
        migrations.AlterField(
            model_name='agentserverbinding',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_bindings', to='core.mcpserver', verbose_name='MCP сервер'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.agent', verbose_name='Агент'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_bases', to='core.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='knowledgechunk',
            name='chunk_index',
            field=models.PositiveIntegerField(verbose_name='Индекс фрагмента'),
        ),
        migrations.AlterField(
            model_name='knowledgechunk',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.knowledgedocument', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='knowledgechunk',
            name='meta',
            field=models.JSONField(blank=True, default=dict, verbose_name='Метаданные'),
        ),
        migrations.AlterField(
            model_name='knowledgechunk',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='knowledgechunk',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='file',
            field=models.FileField(upload_to=core.models.kb_document_path, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='knowledge_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.knowledgebase', verbose_name='База знаний'),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='meta',
            field=models.JSONField(blank=True, default=dict, verbose_name='Метаданные'),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='mime_type',
            field=models.CharField(max_length=255, verbose_name='MIME-тип'),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('processing', 'Обрабатывается'), ('ready', 'Готов'), ('error', 'Ошибка')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='knowledgeembedding',
            name='chunk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='core.knowledgechunk', verbose_name='Фрагмент'),
        ),
        migrations.AlterField(
            model_name='knowledgeembedding',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='knowledgeembedding',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536, verbose_name='Вектор'),
        ),
        migrations.AlterField(
            model_name='mcpserver',
            name='command',
            field=models.CharField(help_text="Команда запуска MCP сервера, например 'uvx' или 'node' или 'python'", max_length=255, verbose_name='Команда запуска'),
        ),
        migrations.AlterField(
            model_name='mcpserver',
            name='command_args',
            field=models.JSONField(default=list, help_text="Список аргументов, например ['mcp-server-filesystem', '--root', '/app/data']", verbose_name='Аргументы команды'),
        ),
        migrations.AlterField(
            model_name='mcpserver',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='mcpserver',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mcpserver',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='mcpserver',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='mcpserver',
            name='transport',
            field=models.CharField(choices=[('stdio', 'STDIO'), ('http', 'HTTP')], default='stdio', max_length=20, verbose_name='Транспорт'),
        ),
        migrations.AlterField(
            model_name='mcpserver',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='mcptool',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='mcptool',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mcptool',
            name='input_schema',
            field=models.JSONField(blank=True, default=dict, verbose_name='Схема входа'),
        ),
        migrations.AlterField(
            model_name='mcptool',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='mcptool',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='mcptool',
            name='output_schema',
            field=models.JSONField(blank=True, default=dict, verbose_name='Схема выхода'),
        ),
        migrations.AlterField(
            model_name='mcptool',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='core.mcpserver', verbose_name='MCP сервер'),
        ),
        migrations.AlterField(
            model_name='mcptool',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='memoryembedding',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='memoryembedding',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536, verbose_name='Вектор'),
        ),
        migrations.AlterField(
            model_name='memoryembedding',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='core.memoryevent', verbose_name='Событие памяти'),
        ),
        migrations.AlterField(
            model_name='memoryevent',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_events', to='core.agent', verbose_name='Агент'),
        ),
        migrations.AlterField(
            model_name='memoryevent',
            name='content',
            field=models.TextField(help_text='Нормализованный факт/предпочтение/задача в человеческом виде', verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='memoryevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='memoryevent',
            name='importance',
            field=models.FloatField(help_text='Важность памяти в диапазоне 0.0–1.0', verbose_name='Важность'),
        ),
        migrations.AlterField(
            model_name='memoryevent',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_events', to='core.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='memoryevent',
            name='type',
            field=models.CharField(choices=[('fact', 'Факт'), ('preference', 'Предпочтение'), ('task', 'Задача')], max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.conversation', verbose_name='Диалог'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='message',
            name='meta',
            field=models.JSONField(blank=True, default=dict, verbose_name='Метаданные'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[('user', 'Пользователь'), ('assistant', 'Ассистент'), ('system', 'Система')], max_length=20, verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='owner_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_pipelines', to='core.agent', verbose_name='Владелец (агент)'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='core.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='pipelinestep',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_steps', to='core.agent', verbose_name='Агент'),
        ),
        migrations.AlterField(
            model_name='pipelinestep',
            name='config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Конфигурация'),
        ),
        migrations.AlterField(
            model_name='pipelinestep',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='pipelinestep',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.pipeline', verbose_name='Пайплайн'),
        ),
        migrations.AlterField(
            model_name='pipelinestep',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_steps', to='core.mcptool', verbose_name='Инструмент'),
        ),
        migrations.AlterField(
            model_name='pipelinestep',
            name='type',
            field=models.CharField(choices=[('agent', 'Агент'), ('tool', 'Инструмент')], max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='core.agent', verbose_name='Создано агентом'),
        ),
        migrations.AlterField(
            model_name='task',
            name='current_step_index',
            field=models.PositiveIntegerField(blank=True, help_text='Индекс (0-based) текущего шага в отсортированном списке steps', null=True, verbose_name='Текущий шаг'),
        ),
        migrations.AlterField(
            model_name='task',
            name='error_message',
            field=models.TextField(blank=True, help_text='Описание ошибки, если статус = error', verbose_name='Сообщение об ошибке'),
        ),
        migrations.AlterField(
            model_name='task',
            name='input_payload',
            field=models.JSONField(default=dict, verbose_name='Входные данные'),
        ),
        migrations.AlterField(
            model_name='task',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.pipeline', verbose_name='Пайплайн'),
        ),
        migrations.AlterField(
            model_name='task',
            name='result_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Результат'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('queued', 'В очереди'), ('running', 'Выполняется'), ('done', 'Готово'), ('error', 'Ошибка')], default='queued', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
