# Generated by Django 5.2.8 on 2025-11-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_agent_options_alter_agentserverbinding_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mcpserver",
            name="base_url",
            field=models.CharField(
                max_length=255,
                blank=True,
                null=True,
                verbose_name="Базовый URL MCP сервера",
                help_text="Например: http://filesystem-mcp:8015/mcp (для HTTP-транспорта)",
            ),
        ),
        migrations.AlterField(
            model_name="mcpserver",
            name="command",
            field=models.CharField(
                max_length=255,
                blank=True,
                null=True,
                verbose_name="Команда запуска",
                help_text=(
                    "Например: python -m core.dummy_mcp_server (для STDIO-транспорта). "
                    "Для HTTP можно оставить пустым."
                ),
            ),
        ),
        migrations.AlterField(
            model_name="mcpserver",
            name="command_args",
            field=models.JSONField(
                blank=True,
                null=True,
                verbose_name="Аргументы команды",
                help_text="Список аргументов для команды (используется только для STDIO-транспорта).",
            ),
        ),
    ]

