# Generated by Django 5.2.8 on 2025-11-26 07:50

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_mcpserver_base_url_charfield_and_command_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcpserver',
            name='base_url',
            field=models.CharField(blank=True, help_text='Например: http://filesystem-mcp:8015/mcp (для HTTP-транспорта)', max_length=255, null=True, validators=[core.models.validate_mcp_base_url], verbose_name='Базовый URL MCP сервера'),
        ),
    ]
