# Generated by Django 5.2.8 on 2025-11-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_mcpserver_base_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentserverbinding',
            name='allowed_tools',
        ),
        migrations.AddField(
            model_name='agentserverbinding',
            name='allowed_tools',
            field=models.ManyToManyField(blank=True, help_text='Инструменты MCP, которые может вызывать агент', related_name='agent_accesses', to='core.mcptool', verbose_name='Разрешённые инструменты'),
        ),
    ]
