# Generated by Django 5.2.8 on 2025-11-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_agentserverbinding_allowed_tools_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='delegates',
            field=models.ManyToManyField(blank=True, related_name='delegated_by', to='core.agent', verbose_name='Агенты, которым можно делегировать задачи'),
        ),
    ]
