# Generated by Django 5.2.8 on 2025-11-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_agent_delegates'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='tool_mode',
            field=models.CharField(choices=[('auto', 'Авто (инструменты по желанию)'), ('required', 'Только через инструменты')], default='auto', help_text="Как агент использует MCP-инструменты и делегатов: 'Авто' — может игнорировать; 'Только через инструменты' — обязан вызывать хотя бы один инструмент.", max_length=16, verbose_name='Режим инструментов'),
        ),
    ]
