# Generated by Django 5.2.8 on 2025-11-28 06:20

import django.contrib.postgres.fields
import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_agent_tool_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memoryevent',
            old_name='source_message',
            new_name='message',
        ),
        migrations.AddField(
            model_name='memoryevent',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory_events', to='core.conversation', verbose_name='Диалог'),
        ),
        migrations.RunSQL(
            "UPDATE core_memoryevent SET importance = LEAST(GREATEST(CEILING(importance), 1), 3);",
            reverse_sql="UPDATE core_memoryevent SET importance = 1;",
        ),
        migrations.AlterField(
            model_name='memoryevent',
            name='importance',
            field=models.PositiveIntegerField(default=1, help_text='Важность памяти (1-3)', verbose_name='Важность'),
        ),
        migrations.AlterField(
            model_name='memoryevent',
            name='type',
            field=models.CharField(choices=[('fact', 'Факт'), ('task', 'Задача'), ('plan', 'План'), ('schema', 'Схема'), ('decision', 'Решение')], max_length=50, verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='AgentMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536, verbose_name='Эмбеддинг')),
                ('importance', models.CharField(choices=[('low', 'Низкая'), ('normal', 'Нормальная'), ('high', 'Высокая')], default='normal', max_length=20, verbose_name='Важность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='core.agent', verbose_name='Агент')),
            ],
            options={
                'verbose_name': 'Долгосрочная память',
                'verbose_name_plural': 'Долгосрочные памяти',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetrievalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(verbose_name='Запрос')),
                ('used_memories', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None, verbose_name='Использованные памяти')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrieval_logs', to='core.agent', verbose_name='Агент')),
            ],
            options={
                'verbose_name': 'Лог выборки памяти',
                'verbose_name_plural': 'Логи выборки памяти',
                'ordering': ['-created_at'],
            },
        ),
    ]
