# Generated by Django 5.2.8 on 2025-11-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_memoryevent_graph_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memoryevent',
            name='graph_processed',
        ),
        migrations.RemoveField(
            model_name='memoryevent',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='project',
            name='graph_processed',
            field=models.BooleanField(default=False, verbose_name='Граф обработан'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
