# Generated by Django 5.2.8 on 2025-11-29 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_knowledgenode_usage_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memoryevent',
            name='graph_processed',
        ),
        migrations.RemoveField(
            model_name='memoryevent',
            name='updated_at',
        ),
    ]
