# Generated by Django 5.2.8 on 2025-11-29 11:48

from django.db import migrations, models
from django.utils.text import slugify


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_memoryevent_graph_processed_and_more'),
    ]

    def populate_slugs(apps, schema_editor):
        Project = apps.get_model("core", "Project")
        for project in Project.objects.all():
            base_slug = slugify(project.name or "") or "project"
            candidate = base_slug[:64]
            counter = 1

            while Project.objects.filter(slug=candidate).exclude(pk=project.pk).exists():
                suffix = f"-{counter}"
                candidate = f"{base_slug[:64 - len(suffix)]}{suffix}"
                counter += 1

            project.slug = candidate
            project.save(update_fields=["slug"])

    operations = [
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, max_length=64, verbose_name="Slug"),
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE "core_project"
                    ADD CONSTRAINT core_project_slug_key UNIQUE ("slug");
                    CREATE INDEX IF NOT EXISTS core_project_slug_pattern
                        ON "core_project" USING btree ("slug" varchar_pattern_ops);
                    """,
                    reverse_sql="""
                    ALTER TABLE "core_project" DROP CONSTRAINT IF EXISTS core_project_slug_key;
                    DROP INDEX IF EXISTS core_project_slug_pattern;
                    """,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="project",
                    name="slug",
                    field=models.SlugField(
                        blank=True,
                        max_length=64,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
            ],
        ),
    ]
