# Generated by Django 5.2.8 on 2024-11-29 00:00

from django.db import migrations, models
from django.utils.text import slugify


def _generate_unique_slug(model, base_value, pk=None, default_name="item", max_length=64):
    base_slug = slugify(base_value or "") or default_name
    base_slug = base_slug[:max_length]
    candidate = base_slug
    counter = 1

    while True:
        qs = model.objects.filter(slug=candidate)
        if pk:
            qs = qs.exclude(pk=pk)
        if not qs.exists():
            return candidate
        suffix = f"-{counter}"
        allowed_len = max_length - len(suffix)
        if allowed_len <= 0:
            candidate = suffix.strip("-")
        else:
            candidate = f"{base_slug[:allowed_len]}{suffix}"
        counter += 1


def populate_slugs(apps, schema_editor):
    MCPServer = apps.get_model("core", "MCPServer")
    Agent = apps.get_model("core", "Agent")
    Project = apps.get_model("core", "Project")

    for server in MCPServer.objects.all():
        server.slug = _generate_unique_slug(
            MCPServer,
            server.name,
            pk=server.pk,
            default_name="mcp-server",
        )
        server.save(update_fields=["slug"])

    for agent in Agent.objects.all():
        project_slug = None
        if agent.project_id:
            project = Project.objects.filter(pk=agent.project_id).first()
            if project:
                project_slug = project.slug

        base_parts = []
        if project_slug:
            base_parts.append(project_slug)
        base_parts.append(agent.name or "agent")
        base_value = "-".join(part for part in base_parts if part)

        agent.slug = _generate_unique_slug(
            Agent,
            base_value,
            pk=agent.pk,
            default_name="agent",
        )
        agent.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_project_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcpserver",
            name="slug",
            field=models.SlugField(blank=True, max_length=64, verbose_name="Slug"),
        ),
        migrations.AddField(
            model_name="mcpserver",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Последняя синхронизация"),
        ),
        migrations.AddField(
            model_name="mcpserver",
            name="last_error",
            field=models.TextField(blank=True, default="", verbose_name="Последняя ошибка"),
        ),
        migrations.AddField(
            model_name="agent",
            name="slug",
            field=models.SlugField(blank=True, max_length=64, verbose_name="Slug"),
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1 FROM pg_constraint
                            WHERE conname = 'core_mcpserver_slug_key'
                        ) THEN
                            ALTER TABLE "core_mcpserver"
                            ADD CONSTRAINT core_mcpserver_slug_key UNIQUE ("slug");
                        END IF;
                    END
                    $$;
                    CREATE INDEX IF NOT EXISTS core_mcpserver_slug_pattern
                        ON "core_mcpserver" ("slug" varchar_pattern_ops);
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1 FROM pg_constraint
                            WHERE conname = 'core_agent_slug_key'
                        ) THEN
                            ALTER TABLE "core_agent"
                            ADD CONSTRAINT core_agent_slug_key UNIQUE ("slug");
                        END IF;
                    END
                    $$;
                    CREATE INDEX IF NOT EXISTS core_agent_slug_pattern
                        ON "core_agent" ("slug" varchar_pattern_ops);
                    """,
                    reverse_sql="""
                    ALTER TABLE "core_mcpserver"
                    DROP CONSTRAINT IF EXISTS core_mcpserver_slug_key;
                    DROP INDEX IF EXISTS core_mcpserver_slug_pattern;
                    ALTER TABLE "core_agent"
                    DROP CONSTRAINT IF EXISTS core_agent_slug_key;
                    DROP INDEX IF EXISTS core_agent_slug_pattern;
                    """,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="mcpserver",
                    name="slug",
                    field=models.SlugField(
                        blank=True,
                        max_length=64,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                migrations.AlterField(
                    model_name="agent",
                    name="slug",
                    field=models.SlugField(
                        blank=True,
                        max_length=64,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
            ],
        ),
    ]
