# Generated by Django 5.2.8 on 2025-11-29 17:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_mcpserver_agent_slugs'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=1024, verbose_name='Путь относительно docs/<slug>')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('content_hash', models.CharField(db_index=True, max_length=64, verbose_name='Хеш содержимого')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME-тип')),
                ('status', models.CharField(choices=[('new', 'New'), ('queued', 'Queued'), ('processed', 'Processed'), ('error', 'Error')], default='new', max_length=20, verbose_name='Статус')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_sources', to='core.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Источник знаний',
                'verbose_name_plural': 'Источники знаний',
                'unique_together': {('project', 'path')},
            },
        ),
    ]
