# Generated by Django 5.2.8 on 2025-11-29 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_knowledgesource'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgechunk',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.knowledgesource', verbose_name='Источник знаний'),
        ),
        migrations.AddField(
            model_name='knowledgeembedding',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embeddings', to='core.knowledgesource', verbose_name='Источник знаний'),
        ),
        migrations.AlterField(
            model_name='knowledgechunk',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.knowledgedocument', verbose_name='Документ'),
        ),
    ]
