# Generated by Django 5.2.8 on 2025-11-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_update_rag_librarian_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rag_error_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество ошибок RAG'),
        ),
        migrations.AddField(
            model_name='project',
            name='rag_last_error_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя ошибка RAG'),
        ),
        migrations.AddField(
            model_name='project',
            name='rag_last_full_sync_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний полный синк RAG'),
        ),
    ]
