# Generated by Django 5.2.8 on 2025-12-01 08:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_project_rag_error_count_project_rag_last_error_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeSourceVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_hash', models.CharField(max_length=64, verbose_name='Хеш содержимого')),
                ('mime_type', models.CharField(blank=True, default='', max_length=100, verbose_name='MIME-тип')),
                ('size_bytes', models.PositiveIntegerField(default=0, verbose_name='Размер, байт')),
                ('text_head', models.TextField(blank=True, default='', verbose_name='Начало текста')),
                ('full_text', models.TextField(blank=True, default='', verbose_name='Полный текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_versions', to='core.project', verbose_name='Проект')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.knowledgesource', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Версия источника',
                'verbose_name_plural': 'Версии источников',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('added', 'Добавлен'), ('modified', 'Изменён'), ('removed', 'Удалён')], max_length=20, verbose_name='Тип изменения')),
                ('diff_text', models.TextField(blank=True, default='', verbose_name='Точный diff')),
                ('semantic_summary', models.TextField(blank=True, default='', verbose_name='Семантическое описание')),
                ('new_facts', models.JSONField(blank=True, default=list, verbose_name='Новые факты')),
                ('removed_facts', models.JSONField(blank=True, default=list, verbose_name='Удалённые факты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_changelog', to='core.project', verbose_name='Проект')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changelog_entries', to='core.knowledgesource', verbose_name='Источник')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_changes', to='core.knowledgesourceversion', verbose_name='Предыдущая версия')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changelog_entries', to='core.knowledgesourceversion', verbose_name='Версия')),
            ],
            options={
                'verbose_name': 'Изменение документации',
                'verbose_name_plural': 'Изменения документации',
                'ordering': ['-created_at'],
            },
        ),
    ]
